### ISSUE TITLE
theme-filtering

### ISSUE THREAD

**Issue by ggggraceful** [sherlock-escape/Sherlock_Back#2]
- [x] 장르 필터 오류 - 밸류 한개일 때는 genre, 여러개면 genreList로 설정해야 작동함
- [x]  평점, 난이도, 예약가능인원 필터 추가 필요

**Comment by soojin-dev** [comment]
장르 필터 오류 - 밸류 한개일 때는 genre, 여러개면 genreList로 설정해야 작동함

**Comment by soo-xz** [comment]
필터 수정 완료
