### ISSUE TITLE
환경변수로 중요키값을 별도로 관리

### ISSUE THREAD

**Issue by moto6** [sherlock-escape/Sherlock_Back#25]
https://github.com/sherlock-escape/Sherlock_Back/blob/1357269d47620ab7d6f9bb5389f14a7c6dd089f2/src/main/resources/application.yml#L54

환경변수로 중요키값을 별도로 관리하는 부분은 잘하셨습니다!

**Comment by ggggraceful** [comment]
감사합니다 ㅎㅎ
