### ISSUE TITLE
JPA Dialect(방언) 지정해주세요

### ISSUE THREAD

**Issue by moto6** [sherlock-escape/Sherlock_Back#26]
https://github.com/sherlock-escape/Sherlock_Back/blob/1357269d47620ab7d6f9bb5389f14a7c6dd089f2/src/main/resources/application.yml#L14

JPA Dialect(방언) 지정을 하면 어떨까요? 당장은 문제가 터지지 않지만, 나중에 엄청난 삽질을 줄여줄 수 있습니다

**Comment by Liam-Geni** [comment]
피드백 참고해서 방언 지정 했습니다.
