### ISSUE TITLE
사용하지 않는 클래스 제거

### ISSUE THREAD

**Issue by moto6** [sherlock-escape/Sherlock_Back#28]
https://github.com/sherlock-escape/Sherlock_Back/blob/1357269d47620ab7d6f9bb5389f14a7c6dd089f2/src/main/java/com/example/sherlockescape/domain/GenrePreference.java#L18

미래에 사용할 계획이 있다면 괜찮은데, 없다면 과감하게 삭제해봅시다!

**Comment by Liam-Geni** [comment]
추후에 사용 할 수 있는 클래스 말고는 과감히 삭제하였습니다.
